#!/usr/bin/env ruby
#
# Flow builder.
#
# Reads a realm's `auth_flows_builder.rb` (a small Ruby program written against
# the DSL in auth_flow_dsl.rb that returns an AuthFlowsTree) and renders two
# artifacts next to it:
#
#   auth_flows_tree.json  the machine-consumed import payload, posted verbatim
#                         to the extension's authentication-flow/import endpoint
#   auth_flows_tree.txt    a human-readable rendering of the same tree — an aid
#                         for reviewing entrypoints, requirements and nesting.
#                         Nothing reads it back; it exists for humans and diffs.
#
# Usage:
#   ruby build_auth_flows.rb [realm-dir]     # defaults to ../demo-realm
require 'json'
require 'set'
require File.join(File.expand_path(File.dirname(__FILE__)), "constants.rb")
require File.join(File.expand_path(File.dirname(__FILE__)), "auth_flow_dsl.rb")

class AuthFlowsBuilder
    # Human-readable rendering of an AuthFlowsTree. Output is for humans only —
    # no reconciliation or validation script consumes it.
    module TreeRenderer
        module_function

        def render(realm, tree)
            flows_by_alias = (tree.authentication_flows || []).each_with_object({}) { |f, h| h[f.alias_name] = f }
            configs_by_alias = (tree.authenticator_configs || []).each_with_object({}) { |c, h| h[c.alias_name] = c }
            entrypoints = entrypoints_by_flow(tree)

            out = []
            out << "# ============================================================================"
            out << "# This file is generated by examples/scripts/build_auth_flows.rb from"
            out << "# auth_flows_builder.rb in this directory. DO NOT EDIT BY HAND."
            out << "#"
            out << "# It is a human-readable aid for reasoning about auth flows (entrypoints,"
            out << "# requirements, subflow nesting). No automation reads it — auth_flows_tree.json"
            out << "# is the machine-consumed source posted to Keycloak."
            out << "# ============================================================================"
            out << ""
            out << "Realm: #{realm}"
            out << ""
            out << "Flow bindings (entrypoints):"
            if tree.flow_binding
                out << "  browserFlow → #{tree.flow_binding}"
            else
                out << "  browserFlow → (none)"
            end
            (tree.idp_flow_bindings || []).each do |b|
                out << "  IDP #{b.alias_name}:"
                out << "    firstLoginFlowBinding → #{b.first_login_flow_binding}" if b.first_login_flow_binding
                out << "    postLoginFlowBinding  → #{b.post_login_flow_binding}" if b.post_login_flow_binding
            end
            out << ""

            top_level = (tree.authentication_flows || []).select(&:top_level)
            if top_level.empty?
                out << "(no top-level flows)"
            else
                top_level.each do |flow|
                    # entrypoints is a Hash.new { |h, k| h[k] = [] } so every key access returns
                    # a (possibly empty) array — guard on emptiness, not truthiness, otherwise the
                    # arrow suffix renders with a trailing space.
                    flow_entrypoints = entrypoints[flow.alias_name]
                    header_suffix = flow_entrypoints.any? ? "  ← #{flow_entrypoints.join(', ')}" : ""
                    out << "#{flow.alias_name}/#{header_suffix}"
                    out.concat(render_flow_body(flow, flows_by_alias, configs_by_alias, "", visited: Set.new([flow.alias_name])))
                    out << ""
                end
            end

            # Normalize the tail to exactly one trailing newline.
            out.join("\n").chomp + "\n"
        end

        def entrypoints_by_flow(tree)
            entries = Hash.new { |h, k| h[k] = [] }
            entries[tree.flow_binding] << "browserFlow" if tree.flow_binding
            (tree.idp_flow_bindings || []).each do |b|
                entries[b.first_login_flow_binding] << "IDP firstLogin (#{b.alias_name})" if b.first_login_flow_binding
                entries[b.post_login_flow_binding] << "IDP postLogin (#{b.alias_name})" if b.post_login_flow_binding
            end
            entries
        end

        def render_flow_body(flow, flows_by_alias, configs_by_alias, prefix, visited:)
            lines = []
            execs = (flow.authentication_executions || []).sort_by { |e| e.priority || 0 }
            execs.each_with_index do |exec, i|
                last = (i == execs.length - 1)
                connector = last ? "└── " : "├── "
                sub_prefix = prefix + (last ? "    " : "│   ")

                if exec.authenticator_flow
                    subflow_alias = exec.flow_alias
                    lines << "#{prefix}#{connector}[#{exec.requirement}] #{subflow_alias}/  (subflow)"
                    sub = flows_by_alias[subflow_alias]
                    if sub.nil?
                        lines << "#{sub_prefix}└── (subflow not found in tree)"
                    elsif visited.include?(subflow_alias)
                        lines << "#{sub_prefix}└── (cycle — already shown above)"
                    else
                        lines.concat(render_flow_body(sub, flows_by_alias, configs_by_alias, sub_prefix, visited: visited + [subflow_alias]))
                    end
                else
                    cfg = exec.authenticator_config
                    cfg_suffix = cfg ? "  (config: #{cfg}#{config_summary(configs_by_alias[cfg])})" : ""
                    lines << "#{prefix}#{connector}[#{exec.requirement}] #{exec.authenticator}#{cfg_suffix}"
                end
            end
            lines
        end

        def config_summary(config_obj)
            return "" unless config_obj && config_obj.config && !config_obj.config.empty?
            kv = config_obj.config.map { |k, v| "#{k}=#{v}" }.join(", ")
            " → #{kv}"
        end
    end

    def self.build(realm_dir)
        realm = File.basename(realm_dir)
        builder_file = File.join(realm_dir, "auth_flows_builder.rb")
        output_file = File.join(realm_dir, "auth_flows_tree.json")
        tree_output_file = File.join(realm_dir, "auth_flows_tree.txt")

        unless File.exist?(builder_file)
            puts "✗ Builder file not found: #{builder_file}"
            return false
        end

        puts "Building auth flows for #{realm}..."
        puts "  → Loading builder: #{builder_file}"

        # Load and execute the builder. It runs against the DSL required above,
        # so `flow`, `subflow`, `auth_flows_tree`, etc. are all in scope.
        tree = eval(File.read(builder_file), binding, builder_file)

        unless tree.is_a?(AuthFlowsTypes::AuthFlowsTree)
            puts "✗ Builder must return an AuthFlowsTree object"
            return false
        end

        # The Keycloak-schema-pure tree (what the import endpoint consumes).
        File.write(output_file, JSON.pretty_generate(tree.to_h) + "\n")
        # The human-readable rendering (not consumed by any automation).
        File.write(tree_output_file, TreeRenderer.render(realm, tree))

        puts "  ✓ Generated #{output_file}"
        puts "  ✓ Generated #{tree_output_file}"
        puts "    → #{tree.authentication_flows.length} flows"
        puts "    → #{tree.authenticator_configs.length} configs"
        puts "    → #{tree.idp_flow_bindings&.length || 0} IDP bindings"
        puts "    → Browser flow binding: #{tree.flow_binding || '(none)'}"

        true
    end
end

if __FILE__ == $0
    realm_dir = ARGV[0] || DEFAULT_REALM_DIR
    exit(AuthFlowsBuilder.build(realm_dir) ? 0 : 1)
end
